# Generated by Django 3.2.7 on 2021-10-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_no', models.CharField(max_length=200)),
                ('bol_no', models.CharField(max_length=200)),
                ('po_name', models.CharField(max_length=200)),
                ('box_number_1', models.CharField(max_length=200)),
                ('box_weight_1', models.CharField(max_length=200)),
                ('box_number_2', models.CharField(max_length=200)),
                ('box_weight_2', models.CharField(max_length=200)),
                ('facility_name', models.CharField(max_length=200)),
                ('approved_miles', models.CharField(max_length=200)),
                ('job_name', models.CharField(max_length=200)),
                ('carrier_name', models.CharField(max_length=200)),
                ('sand_type', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
