# Generated by Django 3.2.7 on 2021-11-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_bol'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='left_on_location_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bol',
            name='left_on_location_2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
