# Generated by Django 3.2.7 on 2021-11-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20211101_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='destination_on',
            field=models.DateTimeField(null=True),
        ),
    ]
