# Generated by Django 3.2.7 on 2021-11-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_destination_on_bol_arrived_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bol',
            name='arrived_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
