# Generated by Django 3.2.7 on 2021-11-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_bol_arrived_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bol',
            name='arrived_time',
            field=models.DateTimeField(null=True),
        ),
    ]
