# Generated by Django 3.2.7 on 2021-11-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_bol_arrived_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='bol_comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
