# Generated by Django 3.2.7 on 2021-11-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_sandtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandtype',
            name='used',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
