# Generated by Django 3.2.7 on 2021-11-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='crew_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
