# Generated by Django 3.2.7 on 2022-01-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_well_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bol',
            old_name='box_number_1',
            new_name='box_number',
        ),
        migrations.RenameField(
            model_name='bol',
            old_name='box_weight_1',
            new_name='box_weight',
        ),
        migrations.RenameField(
            model_name='bol',
            old_name='left_on_location_1',
            new_name='left_on_location',
        ),
        migrations.RemoveField(
            model_name='bol',
            name='box_number_2',
        ),
        migrations.RemoveField(
            model_name='bol',
            name='box_weight_2',
        ),
        migrations.RemoveField(
            model_name='bol',
            name='left_on_location_2',
        ),
    ]
