# Generated by Django 3.2.7 on 2022-01-06 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20220106_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bol',
            name='bol_comment_2',
        ),
    ]
