# Generated by Django 3.2.7 on 2022-01-06 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_bol_bol_comment_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bol',
            old_name='bol_comment_1',
            new_name='bol_comment',
        ),
    ]
