# Generated by Django 3.2.7 on 2022-01-07 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sand_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.bol')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.stage')),
            ],
        ),
    ]
