# Generated by Django 3.2.7 on 2022-01-07 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_stage_bol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='bol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.bol'),
        ),
    ]
