# Generated by Django 3.2.7 on 2022-01-07 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_stage_bol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='bol',
        ),
        migrations.AddField(
            model_name='bol',
            name='stage_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.stage'),
        ),
    ]
