# Generated by Django 3.2.7 on 2022-01-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20220107_0538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sand_Map',
        ),
    ]
