# Generated by Django 3.2.7 on 2022-01-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_delete_sand_map'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Well',
            new_name='Pad',
        ),
    ]
