# Generated by Django 3.2.7 on 2022-01-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_sand_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='sand_map',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
