# Generated by Django 3.2.7 on 2022-01-07 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_sand_map_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sand_map',
            name='stage_number',
        ),
        migrations.RemoveField(
            model_name='sand_map',
            name='well_name',
        ),
        migrations.AddField(
            model_name='sand_map',
            name='bol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.bol'),
        ),
    ]
