# Generated by Django 3.2.7 on 2022-01-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20220107_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='completed',
        ),
        migrations.AddField(
            model_name='sand_map',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='sand_map',
            name='current',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
