# Generated by Django 3.2.7 on 2022-01-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20220107_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='current',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.DeleteModel(
            name='Sand_Map',
        ),
    ]
