# Generated by Django 3.2.7 on 2022-01-07 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20220107_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='stage_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.stage'),
        ),
    ]
