# Generated by Django 3.2.7 on 2022-01-10 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_well_stage_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='current',
        ),
        migrations.RemoveField(
            model_name='well',
            name='stage_number',
        ),
        migrations.CreateModel(
            name='Sand_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False, null=True)),
                ('current', models.BooleanField(default=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.stage')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.well')),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='wells',
            field=models.ManyToManyField(through='projects.Sand_Map', to='projects.Well'),
        ),
        migrations.AddField(
            model_name='well',
            name='stages',
            field=models.ManyToManyField(through='projects.Sand_Map', to='projects.Stage'),
        ),
    ]
