# Generated by Django 3.2.7 on 2022-01-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20220110_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sand_map',
            name='current',
        ),
        migrations.AddField(
            model_name='stage',
            name='current',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='current',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
