# Generated by Django 3.2.7 on 2022-04-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20220110_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pad',
            name='active',
        ),
        migrations.AddField(
            model_name='pad',
            name='working_status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
