# Generated by Django 3.2.7 on 2022-06-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20220411_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='working_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
