# Generated by Django 3.2.7 on 2022-06-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_alter_pad_working_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='working_status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
