# Generated by Django 3.2.7 on 2022-06-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_alter_pad_working_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='si_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
