# Generated by Django 3.2.7 on 2022-06-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_bol_si_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='working_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
