# Generated by Django 3.2.7 on 2022-06-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_sandtype_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sand_Map',
            new_name='Pumped',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='current',
        ),
        migrations.RemoveField(
            model_name='well',
            name='current',
        ),
        migrations.RemoveField(
            model_name='well',
            name='stages',
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_design_sand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='stage_number',
            field=models.ManyToManyField(through='projects.Pumped', to='projects.Stage'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_number',
            field=models.CharField(max_length=50),
        ),
    ]
