# Generated by Django 3.2.7 on 2022-07-01 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20220630_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='wells',
        ),
        migrations.RemoveField(
            model_name='well',
            name='stage_number',
        ),
        migrations.AddField(
            model_name='stage',
            name='well',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.well'),
        ),
        migrations.DeleteModel(
            name='Pumped',
        ),
    ]
