# Generated by Django 3.2.7 on 2022-07-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20220701_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='pad',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
