# Generated by Django 3.2.7 on 2022-07-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_pad_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_design_sand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_number',
            field=models.CharField(max_length=100),
        ),
    ]
